### ISSUE TITLE
More Background Options

### ISSUE THREAD

**Issue by tuminzee** [tuminzee/HitMeWithAnotheOne#3]
Provide more background options, also work on the contrast of colours for dark mode

**Comment by tuminzee** [comment]
I like particles js it has a elegant feel to it

`Ref`
1. https://www.npmjs.com/package/ng-particles
2. https://vincentgarreau.com/particles.js/

**Comment by tuminzee** [comment]
> I like particles js it has a elegant feel to it
> 
> `Ref`
> 
> 1. https://www.npmjs.com/package/ng-particles
> 2. https://vincentgarreau.com/particles.js/

@AA299 let me know what do you think about it.

**Comment by AA299** [comment]
sure sir will let you know soon
